###
# Upload some file
POST http://localhost:3333/api/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFromBoundary7MA4YWxkTrZu0gW

------WebKitFromBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file.http"

< E:\taskforce\project\apps\uploader\src\app\file\file.http
------WebKitFromBoundary7MA4YWxkTrZu0gW--
###

# Get file by ID
GET http://localhost:3333/api/files/6437c9bdaa7ff52ac6fbe090 HTTP/1.1

###
